Bugfix/tp2squadmate locality issues
ArmaOdinDevs/OdinGameMasterAdditions pull request #26
Opened 2023-08-04 21:22 UTC by Crowdedlight

Fixes the issues with showing dialog for local GM and teleporting other players that require server execution. Moved to Rpc through the ``SCR_EditorManagerEntity``.

Also renamed the listbox to better reflect the type of listbox it is.

2023-08-12 20:32 UTC, Kexanone requested changes

2023-08-12 20:32 UTC, Kexanone commented on Scripts/Game/ODIN/Editor/Containers/Actions/ContextActions/ODIN_TeleportToSquadmateContextAction.c
> +		managerEntity.ODIN_TeleportEntityToPlayer(hoveredEntity.GetOwnerRplId(), targetRpl.Id(), emptyTerrainAreaRadius);
`emptyTerrainAreaRadius` is a constant, hence should be moved to `SCR_EditorManagerEntity`

2023-08-12 20:32 UTC, Kexanone commented on Scripts/Game/ODIN/Editor/Entities/SCR_EditorManagerEntity.c
> +	void ODIN_SetTransform(IEntity sourceEntity, vector transform[4])
What's the point of this function? Why not just call `SCR_EditableEntityComponent.SetTransform` directly?

2023-08-13 10:27 UTC, Crowdedlight commented
Addressed Review comments. @Kexanone

2023-08-13 15:40 UTC, Kexanone requested changes

2023-08-13 15:40 UTC, Kexanone commented on Scripts/Game/ODIN/Editor/Entities/SCR_EditorManagerEntity.c
> +	static int emptyTerrainAreaRadius = 20;
Should be prefixed

2023-08-13 15:46 UTC, Kexanone approved these changes

2023-08-13 15:46 UTC, merged